### ISSUE TITLE
Fix R CMD CHECK and roxgen issues

### ISSUE THREAD

**Issue by amoeba** [NCEAS/arcticdatautils#66]
Running R CMD CHECK and `devtools::document()` have been broken for a long time because I haven't had the time to fix the issues. But it's super confusing for others when there are issues because they can't see if their changes are problematic if there is already a slew of problems.

Fix issues until these operations no longer yield errors/warnings.

**Comment by jeanetteclark** [comment]
@amoeba I'm looking into this one as I am able to. I can't self-assign

**Comment by jeanetteclark** [comment]
I think this is complete - issues are fixed and no warnings show up. Ready to close this one @amoeba?

**Comment by amoeba** [comment]
Awesome, I'll take a look now and close this.

**Comment by amoeba** [comment]
I still see 2 warnings, which are counted as errors on Travis. I can fix this up later today unless you'd like to.

**Comment by amoeba** [comment]
PS: The reason it's nice to get Travis succeeding is so, when PRs come in and the PR triggers a Travis build, if the build fails, the person knows their PR caused the failure and the maintainer can know not to merge the PR.

**Comment by jeanetteclark** [comment]
When do you see the warnings? when I ran this on my branch I didn't get any warnings when I run devtools::documents() but maybe I missed a step in document fixing

**Comment by amoeba** [comment]
Hrm, I ran it on `master` a bit ago,

> R CMD check results
> 0 errors | 2 warnings | 4 notes
>
> R CMD check succeeded

It looks like the warnings are line length issues and missing @params.

**Comment by jeanetteclark** [comment]
I'll pull from upstream and check again tomorrow. Do you just run devtools::documents() in the console?

**Comment by amoeba** [comment]
`devtools::check()`, and I usually just click the Check button in the Build tab in RStudio. Thanks!

**Comment by amoeba** [comment]
All good. Thanks a ton @jeanetteclark. This was a big time saver.
